# Generated by Django 5.2.8 on 2025-12-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image_paymentaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for Mpesa payments (format: 254...)', max_length=20),
        ),
    ]
