# Generated by Django 5.2.8 on 2025-11-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('jewelry', 'Jewelry'), ('vehicle', 'Vehicle'), ('pet', 'Pet'), ('clothing', 'Clothing'), ('money', 'Money/Wallet'), ('keys', 'Keys'), ('phone', 'Phone'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='date_item_lost_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='item_type',
            field=models.CharField(choices=[('lost', 'Lost Item'), ('found', 'Found Item')], default='lost', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Kenya', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
